# Generated by Django 4.1.7 on 2023-03-09 23:58

import bson.objectid
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomIdentifyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroom',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False),
        ),
    ]
