# Generated by Django 4.1.7 on 2023-03-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomIdentifyer', '0003_alter_mushroom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
