# Generated by Django 4.1.7 on 2023-03-10 00:22

import bson.objectid
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomIdentifyer', '0004_alter_mushroom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroom',
            name='id',
        ),
        migrations.AddField(
            model_name='mushroom',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
    ]
