# Generated by Django 4.1.7 on 2023-03-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomIdentifyer', '0005_remove_mushroom_id_mushroom__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mushroom',
            old_name='_id',
            new_name='id',
        ),
    ]
