# Generated by Django 4.1.7 on 2023-03-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomIdentifyer', '0006_rename__id_mushroom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroom',
            name='latin_name',
            field=models.CharField(default='fill_value', max_length=255),
            preserve_default=False,
        ),
    ]
