# Generated by Django 4.1.7 on 2023-03-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomIdentifyer', '0008_alter_mushroom_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mushroom',
            old_name='latin_name',
            new_name='s_name',
        ),
        migrations.RemoveField(
            model_name='mushroom',
            name='area',
        ),
        migrations.RemoveField(
            model_name='mushroom',
            name='edible',
        ),
        migrations.RemoveField(
            model_name='mushroom',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='mushroom',
            name='poisonous',
        ),
        migrations.AddField(
            model_name='mushroom',
            name='comment',
            field=models.TextField(default='No data'),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='image_urls',
            field=models.URLField(default='No data'),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='list_mislabel',
            field=models.URLField(default='No data'),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='nsnf_norm',
            field=models.TextField(default='No data'),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='recipe',
            field=models.TextField(default='No data'),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='description',
            field=models.TextField(default='No data'),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
